### ISSUE TITLE
eigen link broken in readme

### ISSUE THREAD

**Issue by mfe7** [roboticsengineer93/vins-fusion-gpu-tx2#1]
thanks for this great repo. i'm just getting started with it, but so far i see that the link to eigen was broken (moved to gitlab). the following two lines in the readme could be updated to reflect this change:

- change `wget -O eigen.zip http://bitbucket.org/eigen/eigen/get/3.3.7.zip` to `wget -O eigen.zip https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip`
- `unzip eigen.zip -d eigen-3.3.7` to `unzip eigen.zip`

**Comment by arjunskumar** [comment]
Thanks @mfe7 . Updated the readme.
