### ISSUE TITLE
branch of vision_opencv

### ISSUE THREAD

**Issue by mfe7** [roboticsengineer93/vins-fusion-gpu-tx2#2]
another suggestion is to add `-b melodic` to the `git clone` of `vision_opencv` since the current default branch is `noetic` which causes some compilation issues

**Comment by mfe7** [comment]
also, i also didn't need to change the `CMakeLists.txt` of the vins packages. maybe that repo updated the paths in the meantime?

**Comment by arjunskumar** [comment]
@mfe7 Thanks for pointing out.  Since I'm not working on vins +Jetson platforms, there may be broken links/package branch changes. I will update the docs when I will test it on Jeston Xavier NX.

**Comment by mfe7** [comment]
makes sense, just wanted to make note of these in case someone else tries it out. i really appreciate that you've made this repo!
