### ISSUE TITLE
Time delay of track image

### ISSUE THREAD

**Issue by a828933858** [roboticsengineer93/vins-fusion-gpu-tx2#4]
Hello, I compiled all steps successfully, unfortunately, I found the track image had more than a 10-second delay. Does this also happen on your Nano?  The usage of all four CPUs reaches above 95%, but GPU is around 50%.

**Comment by arjunskumar** [comment]
@a828933858  adding this in your node will reduce CPU usage ` cv::setNumThreads(1);`
