### ISSUE TITLE
make test failed when compling ceres

### ISSUE THREAD

**Issue by J1dan** [roboticsengineer93/vins-fusion-gpu-tx2#6]
I intalled eigen 3.3.7 and compiled ceres 1.14.0 but when I make test it printed the following message:

_99% tests passed, 1 tests failed out of 127

Total Test time (real) = 338.14 sec

The following tests FAILED:
	 30 - evaluation_callback_test (Failed)
Errors while running CTest
Makefile:85: recipe for target 'test' failed
make: *** [test] Error 8_

Do you know what's wrong? Thanks a lot

**Comment by arjunskumar** [comment]
@J1dan I think its okay that some tests may fail. please continue with the rest of the steps
